
export const initialData = {
  interns: [
    { id: 1, name: "Alice Johnson", email: "alice.j@example.com", project: "AI Chatbot Integration", mentor: "Dr. Guide", status: "Active", ppoStatus: "Pending" },
    { id: 2, name: "Bob Williams", email: "bob.w@example.com", project: "Data Analytics Dashboard", mentor: "Jane Doe", status: "Active", ppoStatus: "Pending" },
    { id: 3, name: "Charlie Brown", email: "charlie.b@example.com", project: "Mobile App Redesign", mentor: "John Smith", status: "Completed", assessmentScore: 92, ppoStatus: "Recommended", ppoReasoning: "Exceeded all project goals and was a great team player." },
    { id: 4, name: "Diana Miller", email: "diana.m@example.com", project: "UI/UX Improvement", mentor: "Emily White", status: "Active", ppoStatus: "Pending" },
    { id: 5, name: "Ethan Davis", email: "ethan.d@example.com", project: "Cloud Migration Strategy", mentor: "Michael Green", status: "On-Hold", ppoStatus: "Not Recommended", ppoReasoning: "Project was put on hold, insufficient data to make a recommendation." },
    { id: 6, name: "Fiona Garcia", email: "fiona.g@example.com", project: "AI Chatbot Integration", mentor: "Dr. Guide", status: "Active", ppoStatus: "Pending" },
    { id: 7, name: "George Rodriguez", email: "george.r@example.com", project: "Data Analytics Dashboard", mentor: "Jane Doe", status: "Active", ppoStatus: "Pending" },
    { id: 8, name: "Hannah Martinez", email: "hannah.m@example.com", project: "Mobile App Redesign", mentor: "John Smith", status: "Completed", assessmentScore: 85, ppoStatus: "Recommended", ppoReasoning: "Consistently delivered high-quality work and showed great potential." },
    { id: 9, name: "Ian Hernandez", email: "ian.h@example.com", project: "UI/UX Improvement", mentor: "Emily White", status: "Active", ppoStatus: "Pending" },
    { id: 10, name: "Jasmine Lopez", email: "jasmine.l@example.com", project: "Cloud Migration Strategy", mentor: "Michael Green", status: "Active", ppoStatus: "Pending" },
  ],
  mentors: [
    { id: 1, name: "Dr. Guide", email: "mentor@synergy.com", expertise: "AI/ML", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { id: 2, name: "Jane Doe", email: "jane.d@synergy.com", expertise: "Data Science", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { id: 3, name: "John Smith", email: "john.s@synergy.com", expertise: "Mobile Development", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { id: 4, name: "Emily White", email: "emily.w@synergy.com", expertise: "UI/UX Design", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { id: 5, name: "Michael Green", email: "michael.g@synergy.com", expertise: "Cloud Architecture", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { id: 6, name: "Sarah Black", email: "sarah.b@synergy.com", expertise: "Backend Systems", interns: 0, avatar: "https://placehold.co/100x100.png" },
    { id: 7, name: "David King", email: "david.k@synergy.com", expertise: "DevOps", interns: 0, avatar: "https://placehold.co/100x100.png" },
    { id: 8, name: "Laura Hill", email: "laura.h@synergy.com", expertise: "Product Management", interns: 0, avatar: "https://placehold.co/100x100.png" },
    { id: 9, name: "Kevin Scott", email: "kevin.s@synergy.com", expertise: "Cybersecurity", interns: 0, avatar: "https://placehold.co/100x100.png" },
    { id: 10, name: "Olivia Adams", email: "olivia.a@synergy.com", expertise: "Frontend Development", interns: 0, avatar: "https://placehold.co/100x100.png" },
  ],
  projects: [
    { 
      id: 1, 
      title: "AI Chatbot Integration", 
      description: "Integrate a new AI-powered chatbot into the customer support platform.", 
      status: "In Progress", 
      team: ["Alice Johnson", "Fiona Garcia"], 
      mentor: "Dr. Guide",
      document: "https://example.com/chatbot-brief.pdf",
      recentActivity: "Pushed new intent recognition model.",
      tasks: [
        { id: 1, title: "Setup chatbot framework", completed: true },
        { id: 2, title: "Integrate with Zendesk API", completed: true },
        { id: 3, title: "Train initial intent model", completed: true },
        { id: 4, title: "Design conversation flows", completed: true },
        { id: 5, title: "Implement user feedback mechanism", completed: true },
        { id: 6, title: "Develop analytics dashboard for chatbot", completed: false },
        { id: 7, title: "Test conversation flows", completed: true },
        { id: 8, title: "Deploy chatbot to staging", completed: false },
        { id: 9, title: "Write documentation", completed: false },
        { id: 10, title: "Final UAT with support team", completed: false },
        { id: 11, title: "Prepare production launch plan", completed: false },
        { id: 12, title: "Analyze post-launch metrics", completed: false }
      ]
    },
    { 
      id: 2, 
      title: "Data Analytics Dashboard", 
      description: "Develop a dashboard for visualizing key business metrics and KPIs.", 
      status: "In Progress", 
      team: ["Bob Williams", "George Rodriguez"], 
      mentor: "Jane Doe",
      document: null,
      recentActivity: "Added new chart for user engagement.",
      tasks: [
        { id: 1, title: "Define key metrics (KPIs)", completed: true },
        { id: 2, title: "Setup data pipeline from production DB", completed: true },
        { id: 3, title: "Choose a data visualization library", completed: true },
        { id: 4, title: "Design dashboard layout", completed: true },
        { id: 5, title: "Implement date range filter", completed: true },
        { id: 6, title: "Add chart for user growth", completed: false },
        { id: 7, title: "Add chart for revenue", completed: false },
        { id: 8, title: "Add chart for user engagement", completed: false },
        { id: 9, title: "Implement user authentication for dashboard", completed: false },
        { id: 10, title: "Optimize dashboard loading performance", completed: false },
        { id: 11, title: "Test dashboard with live data", completed: false },
        { id: 12, title: "Gather feedback from stakeholders", completed: false },
        { id: 13, title: "Deploy to production", completed: false },
        { id: 14, title: "Create user guide for the dashboard", completed: false },
        { id: 15, title: "Set up automated daily reports", completed: false }
      ]
    },
    { 
      id: 3, 
      title: "Mobile App Redesign", 
      description: "Complete redesign of the flagship mobile application for iOS and Android.", 
      status: "Completed", 
      team: ["Charlie Brown", "Hannah Martinez"], 
      mentor: "John Smith",
      document: "https://example.com/mobile-redesign-spec.pdf",
      recentActivity: "Final version approved and merged.",
      tasks: Array.from({ length: 20 }, (_, i) => ({
        id: i + 1,
        title: `Completed Task ${i + 1}`,
        completed: true
      }))
    },
    { id: 4, title: "UI/UX Improvement", description: "Conduct user research and implement UI/UX improvements across the website.", status: "In Progress", progress: 75, team: ["Diana", "Ian"], mentor: "Emily White", tasks: [] },
    { id: 5, title: "Cloud Migration Strategy", description: "Plan and execute the migration of legacy systems to a cloud-based infrastructure.", status: "On-Hold", progress: 20, team: ["Ethan", "Jasmine"], mentor: "Michael Green", tasks: [] },
    { id: 6, title: "E-commerce Platform", description: "Build a new e-commerce platform from scratch.", status: "Not Started", progress: 0, team: [], mentor: "Sarah Black", tasks: [] },
    { id: 7, title: "Internal Tooling", description: "Develop internal tools to improve developer productivity.", status: "In Progress", progress: 80, team: [], mentor: "David King", tasks: [] },
    { id: 8, title: "API Security Audit", description: "Perform a comprehensive security audit of all public-facing APIs.", status: "In Progress", progress: 30, team: [], mentor: "Kevin Scott", tasks: [] },
    { id: 9, title: "Marketing Website", description: "Create a new marketing website to showcase products.", status: "Completed", progress: 100, team: [], mentor: "Olivia Adams", tasks: [] },
    { id: 10, title: "Onboarding Flow", description: "Redesign the user onboarding flow for new customers.", status: "Not Started", progress: 0, team: [], mentor: "Emily White", tasks: [] },
  ],
  applications: [
    { id: 1, name: "Liam Smith", university: "Tech University", date: "2024-06-01", status: "Pending" },
    { id: 2, name: "Olivia Jones", university: "State College", date: "2024-06-02", status: "Reviewed" },
    { id: 3, name: "Noah Taylor", university: "Ivy League Institute", date: "2024-06-02", status: "Accepted" },
    { id: 4, name: "Emma Brown", university: "City University", date: "2024-06-03", status: "Rejected" },
    { id: 5, name: "Oliver Wilson", university: "Tech University", date: "2024-06-04", status: "Pending" },
    { id: 6, name: "Ava Garcia", university: "State College", date: "2024-06-05", status: "Pending" },
    { id: 7, name: "Elijah Martinez", university: "Ivy League Institute", date: "2024-06-05", status: "Reviewed" },
    { id: 8, name: "Sophia Anderson", university: "City University", date: "2024-06-06", status: "Accepted" },
    { id: 9, name: "James Thomas", university: "Tech University", date: "2024-06-07", status: "Pending" },
    { id: 10, name: "Isabella Hernandez", university: "State College", date: "2024-06-08", status: "Rejected" },
  ]
};
