export const initialData = {
  interns: [
    { _id: "669a8e5a5b5e3c8b4b7a1b1a", id: 1, name: "Alice Johnson", email: "intern@synergy.com", project: "AI Chatbot Integration", mentor: "Dr. Guide", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b1b", id: 2, name: "Bob Williams", email: "bob.w@example.com", project: "Data Analytics Dashboard", mentor: "Jane Doe", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b1c", id: 3, name: "Charlie Brown", email: "charlie.b@example.com", project: "Mobile App Redesign", mentor: "John Smith", status: "Completed", assessmentScore: 92, ppoStatus: "Recommended", ppoReasoning: "Exceeded all project goals and was a great team player." },
    { _id: "669a8e5a5b5e3c8b4b7a1b1d", id: 4, name: "Diana Miller", email: "diana.m@example.com", project: "UI/UX Improvement", mentor: "Emily White", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b1e", id: 5, name: "Ethan Davis", email: "ethan.d@example.com", project: "Cloud Migration Strategy", mentor: "Michael Green", status: "On-Hold", ppoStatus: "Not Recommended", ppoReasoning: "Project was put on hold, insufficient data to make a recommendation." },
    { _id: "669a8e5a5b5e3c8b4b7a1b1f", id: 6, name: "Fiona Garcia", email: "fiona.g@example.com", project: "AI Chatbot Integration", mentor: "Dr. Guide", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b20", id: 7, name: "George Rodriguez", email: "george.r@example.com", project: "Data Analytics Dashboard", mentor: "Jane Doe", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b21", id: 8, name: "Hannah Martinez", email: "hannah.m@example.com", project: "Mobile App Redesign", mentor: "John Smith", status: "Completed", assessmentScore: 85, ppoStatus: "Recommended", ppoReasoning: "Consistently delivered high-quality work and showed great potential." },
    { _id: "669a8e5a5b5e3c8b4b7a1b22", id: 9, name: "Ian Hernandez", email: "ian.h@example.com", project: "UI/UX Improvement", mentor: "Emily White", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b23", id: 10, name: "Jasmine Lopez", email: "jasmine.l@example.com", project: "Cloud Migration Strategy", mentor: "Michael Green", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b24", id: 11, name: "Ken Adams", email: "ken.a@example.com", project: "E-commerce Platform", mentor: "Sarah Black", status: "Active", ppoStatus: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b25", id: 12, name: "Laura Hill", email: "laura.h@example.com", project: "Internal Tooling", mentor: "David King", status: "Active", ppoStatus: "Pending" },
  ],
  mentors: [
    { _id: "669a8e5a5b5e3c8b4b7a1b26", id: 1, name: "Dr. Guide", email: "mentor@synergy.com", expertise: "AI/ML", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b27", id: 2, name: "Jane Doe", email: "jane.d@synergy.com", expertise: "Data Science", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b28", id: 3, name: "John Smith", email: "john.s@synergy.com", expertise: "Mobile Development", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b29", id: 4, name: "Emily White", email: "emily.w@synergy.com", expertise: "UI/UX Design", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b2a", id: 5, name: "Michael Green", email: "michael.g@synergy.com", expertise: "Cloud Architecture", interns: 2, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b2b", id: 6, name: "Sarah Black", email: "sarah.b@synergy.com", expertise: "Backend Systems", interns: 1, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b2c", id: 7, name: "David King", email: "david.k@synergy.com", expertise: "DevOps", interns: 1, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b2d", id: 8, name: "Laura Hill", email: "laura.h@synergy.com", expertise: "Product Management", interns: 0, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b2e", id: 9, name: "Kevin Scott", email: "kevin.s@synergy.com", expertise: "Cybersecurity", interns: 0, avatar: "https://placehold.co/100x100.png" },
    { _id: "669a8e5a5b5e3c8b4b7a1b2f", id: 10, name: "Olivia Adams", email: "olivia.a@synergy.com", expertise: "Frontend Development", interns: 0, avatar: "https://placehold.co/100x100.png" },
  ],
  projects: [
    { _id: "669a8e5a5b5e3c8b4b7a1b30", id: 1, title: "AI Chatbot Integration", description: "Integrate a third-party AI chatbot.", status: "In Progress", team: ["Alice Johnson", "Fiona Garcia"], mentor: "Dr. Guide", document: "https://example.com/chatbot-brief.pdf", recentActivity: "Fiona pushed new changes", tasks: [
        { id: 1, title: 'Research chatbot APIs', completed: true },
        { id: 2, title: 'Initial API integration', completed: true },
        { id: 3, title: 'Develop UI components', completed: false },
        { id: 4, title: 'Test and debug', completed: false },
    ] },
    { _id: "669a8e5a5b5e3c8b4b7a1b31", id: 2, title: "Data Analytics Dashboard", description: "Build a dashboard for internal metrics.", status: "In Progress", team: ["Bob Williams", "George Rodriguez"], mentor: "Jane Doe", document: null, recentActivity: "Bob fixed a bug", tasks: [
        { id: 1, title: 'Define key metrics', completed: true },
        { id: 2, title: 'Design dashboard layout', completed: true },
        { id: 3, title: 'Implement data fetching', completed: true },
        { id: 4, title: 'Create chart components', completed: false },
        { id: 5, title: 'Add filters and controls', completed: false },
    ] },
    { _id: "669a8e5a5b5e3c8b4b7a1b32", id: 3, title: "Mobile App Redesign", description: "Redesign the main mobile application.", status: "Completed", team: ["Charlie Brown", "Hannah Martinez"], mentor: "John Smith", document: "https://example.com/mobile-spec.pdf", recentActivity: "Hannah merged final PR", tasks: [
        { id: 1, title: 'User research', completed: true },
        { id: 2, title: 'Create wireframes', completed: true },
        { id: 3, title: 'Develop new UI kit', completed: true },
        { id: 4, title: 'Implement new screens', completed: true },
        { id: 5, title: 'Conduct user testing', completed: true },
    ] },
    { _id: "669a8e5a5b5e3c8b4b7a1b33", id: 4, title: "UI/UX Improvement", description: "A project to improve UI/UX.", status: "In Progress", team: ["Diana Miller", "Ian Hernandez"], mentor: "Emily White", document: null, recentActivity: "Diana created new mockups", tasks: [
        { id: 1, title: 'Component audit', completed: true },
        { id: 2, title: 'User feedback session', completed: false },
        { id: 3, title: 'Prototype new designs', completed: false },
    ] },
    { _id: "669a8e5a5b5e3c8b4b7a1b34", id: 5, title: "Cloud Migration Strategy", description: "Develop a strategy for cloud migration.", status: "On-Hold", team: ["Ethan Davis", "Jasmine Lopez"], mentor: "Michael Green", document: null, recentActivity: "Project paused", tasks: [
        { id: 1, title: 'Analyze current infrastructure', completed: true },
        { id: 2, title: 'Evaluate cloud providers', completed: false },
    ] },
  ],
  applications: [
    { _id: "669a8e5a5b5e3c8b4b7a1b35", name: "Liam Smith", university: "Tech University", date: "2024-06-01", status: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b36", name: "Olivia Jones", university: "State College", date: "2024-06-02", status: "Reviewed" },
    { _id: "669a8e5a5b5e3c8b4b7a1b37", name: "Noah Taylor", university: "Ivy League Institute", date: "2024-06-02", status: "Accepted" },
    { _id: "669a8e5a5b5e3c8b4b7a1b38", name: "Emma Brown", university: "City University", date: "2024-06-03", status: "Rejected" },
    { _id: "669a8e5a5b5e3c8b4b7a1b39", name: "Oliver Wilson", university: "Tech University", date: "2024-06-04", status: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b3a", name: "Ava Garcia", university: "State College", date: "2024-06-05", status: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b3b", name: "Elijah Martinez", university: "Ivy League Institute", date: "2024-06-05", status: "Reviewed" },
    { _id: "669a8e5a5b5e3c8b4b7a1b3c", name: "Sophia Anderson", university: "City University", date: "2024-06-06", status: "Accepted" },
    { _id: "669a8e5a5b5e3c8b4b7a1b3d", name: "James Thomas", university: "Tech University", date: "2024-06-07", status: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b3e", name: "Isabella Hernandez", university: "State College", date: "2024-06-08", status: "Rejected" },
    { _id: "669a8e5a5b5e3c8b4b7a1b3f", name: "William Moore", university: "Metro University", date: "2024-06-09", status: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b40", name: "Mia Clark", university: "National University", date: "2024-06-10", status: "Pending" },
    { _id: "669a8e5a5b5e3c8b4b7a1b41", name: "Benjamin Lewis", university: "Coastal University", date: "2024-06-11", status: "Reviewed" },
    { _id: "669a8e5a5b5e3c8b4b7a1b42", name: "Charlotte Hall", university: "Mountain State", date: "2024-06-12", status: "Accepted" },
  ]
};
